api:
  api_key: "your-api-key-here"  # 请替换为您的实际 API 密钥
  base_url: "https://api.deepseek.com/v1"
  model: "deepseek-chat"
  temperature: 0.7
  max_tokens: 2000
  top_p: 0.9

paths:
  input_dir: "data/input"
  output_dir: "data/output"

generation:
  temperature: 0.7
  max_tokens: 4000
  top_p: 0.95 