api:
  base_url: ${DEEPSEEK_API_BASE}
  api_key: ${DEEPSEEK_API_KEY}
  model: "deepseek-chat"

paths:
  input_dir: "data/input"
  output_dir: "data/output"

generation:
  temperature: 0.7
  max_tokens: 4000
  top_p: 0.95 